### ISSUE TITLE
Change QC Report structure from List to Dict

### ISSUE THREAD

**Issue by amc-corey-cox** [monarch-initiative/cat-merge#41]
Top Level Qc Report structure is currently a list but will have greater utility as a dict. This shouldn't be too big a change but requires testing and re-validating the QC Report Diff functionality.

**Comment by caufieldjh** [comment]
Literally just ran into this minutes ago here (https://github.com/ncbo/kg-bioportal/pull/42) so will be looking forward to the fix!

**Comment by amc-corey-cox** [comment]
closed with PR https://github.com/monarch-initiative/cat-merge/pull/45
@caufieldjh

**Comment by caufieldjh** [comment]
Excellent, thanks!
